from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from datetime import datetime
import os

def create_report(filename, report_title, stats, top_malicious_ips, graph_paths):
    """
    สร้างรายงานสรุปในรูปแบบไฟล์ PDF, now fully robust to handle dict-like objects.
    """
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # --- Header ---
    c.setFont("Helvetica-Bold", 18)
    c.drawString(inch, height - 1*inch, "LOCKON IP Prism - Executive Summary")
    c.setFont("Helvetica", 12)
    c.drawString(inch, height - 1.25*inch, f"Report Title: {report_title}")
    c.drawString(inch, height - 1.45*inch, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.line(inch, height - 1.6*inch, width - inch, height - 1.6*inch)

    # --- Key Metrics ---
    y_pos = height - 2.2*inch
    c.setFont("Helvetica-Bold", 14)
    c.drawString(inch, y_pos, "Key Metrics")
    
    c.setFont("Helvetica", 12)
    c.drawString(1.2*inch, y_pos - 0.3*inch, f"• Total Unique IPs Analyzed: {stats.get('total_ips', 0)}")
    c.drawString(1.2*inch, y_pos - 0.5*inch, f"• Malicious IPs Detected: {stats.get('malicious_count', 0)}")
    c.drawString(1.2*inch, y_pos - 0.7*inch, f"• Top Malicious Country: {stats.get('top_country', 'N/A')}")
    
    # --- Graphs ---
    y_pos -= 1.2*inch
    c.setFont("Helvetica-Bold", 14)
    c.drawString(inch, y_pos, "Visualizations")

    if 'pie_chart' in graph_paths and os.path.exists(graph_paths['pie_chart']):
        c.drawImage(graph_paths['pie_chart'], inch, y_pos - 2.7*inch, width=3.5*inch, height=2.5*inch, preserveAspectRatio=True)
    if 'bar_chart' in graph_paths and os.path.exists(graph_paths['bar_chart']):
        c.drawImage(graph_paths['bar_chart'], inch + 4*inch, y_pos - 2.7*inch, width=3*inch, height=2.4*inch, preserveAspectRatio=True)

    # --- Top Malicious IPs Table ---
    y_pos -= 3.2*inch
    c.setFont("Helvetica-Bold", 14)
    c.drawString(inch, y_pos, "Top 10 High-Risk IPs")

    table_data = [['IP Address', 'Country', 'ISP', 'Score', 'OTX']]
    for ip_data in top_malicious_ips:
        # --- FIXED: Use direct key access which works for both dict and sqlite3.Row ---
        # The 'or' operator provides a safe fallback for None values.
        table_data.append([
            ip_data['ip_address'] or '',
            ip_data['country'] or 'N/A',
            ip_data['isp'] or '',
            ip_data['fraud_score'] or 0,
            ip_data['otx_pulses'] or 0
        ])

    table = Table(table_data, colWidths=[1.5*inch, 1*inch, 2.5*inch, 0.7*inch, 0.6*inch])
    style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR',(0,0),(-1,0),colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ])
    table.setStyle(style)

    table.wrapOn(c, width, height)
    table.drawOn(c, inch, y_pos - (len(table_data) * 0.25 + 0.3)*inch)

    # --- Footer ---
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(inch, 0.5*inch, f"Generated by LOCKON IP Prism v2.2")

    c.save()
    
    # --- Cleanup temporary graph files ---
    for path in graph_paths.values():
        if os.path.exists(path):
            try:
                os.remove(path)
            except OSError as e:
                print(f"Error cleaning up temp graph file {path}: {e}")

